AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'dimby-api

  Sample SAM Template for dimby-api

  '
Globals:
  Function:
    Timeout: 3
Resources:
  DimbyApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://kujo4pm-lambda-deploys/a39903fcaad93764212b1fa6f30093fe
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        DimbyApi:
          Type: Api
          Properties:
            Path: /api
            Method: get
Outputs:
  DimbyApi:
    Description: API Gateway endpoint URL for Prod stage for Dimby API function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/
  DimbyApiFunction:
    Description: Dimby Api Lambda Function ARN
    Value:
      Fn::GetAtt:
      - DimbyApiFunction
      - Arn
  DimbyApiFunctionIamRole:
    Description: Implicit IAM Role created for Dimby API function
    Value:
      Fn::GetAtt:
      - DimbyApiFunctionRole
      - Arn
