AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'dimby-api

  Sample SAM Template for sam-app

  '
Globals:
  Api:
    Cors:
      AllowMethods: '''OPTIONS,POST,GET'''
      AllowHeaders: '''Content-Type,Authorization,Access-Control-Allow-Origin'''
      AllowOrigin: '''*'''
  Function:
    Timeout: 8
Resources:
  DimbyApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://kujo4pm-lambda-deploys/863ce05f001f119eb0bfcb82de33cb43
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        DimbyApi:
          Type: Api
          Properties:
            Path: /api
            Method: get
Outputs:
  DimbyApi:
    Description: API Gateway endpoint URL for Prod stage for Dimby API function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/
  DimbyApiFunction:
    Description: Dimby API Lambda Function ARN
    Value:
      Fn::GetAtt:
      - DimbyApiFunction
      - Arn
  DimbyApiFunctionIamRole:
    Description: Implicit IAM Role created for Dimby Api function
    Value:
      Fn::GetAtt:
      - DimbyApiFunctionRole
      - Arn
