AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'dimby-api

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: '''DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'''
      AllowHeaders: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
      AllowOrigin: '''*'''
Resources:
  DimbyApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://kujo4pm-lambda-deploys/7a99aacda7da84a65527cb944ad112c3
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        DimbyApi:
          Type: Api
          Properties:
            Path: /api
            Method: get
Outputs:
  DimbyApi:
    Description: API Gateway endpoint URL for Prod stage for Dimby API function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/
  DimbyApiFunction:
    Description: Dimby API Lambda Function ARN
    Value:
      Fn::GetAtt:
      - DimbyApiFunction
      - Arn
  DimbyApiFunctionIamRole:
    Description: Implicit IAM Role created for Dimby Api function
    Value:
      Fn::GetAtt:
      - DimbyApiFunctionRole
      - Arn
